### ISSUE TITLE
Unable to install an extension using home manager.

### ISSUE THREAD

**Issue by laycookie** [schizofox/schizofox#114]
I and a couple different other people who are trying out schizofox had trouble figuring out how to install extensions in declarative way. Is it possible to add comments about it this in the README example?

So far those are the points of confusion.
- "what extensions can I add in the extensions sections and what extensions do I need to add in extraExtensions"
- What does `"webextension@metamask.io".install_url` how do I know what the string should be for my file extension.

and my point of confusion is why does this not install proton pass for me?
```nix
	  extensions.extraExtensions = {
		"webextension@proton.me".install_url = "https://addons.mozilla.org/firefox/downloads/latest/proton-pass/latest.xpi";
	  };
```

**Comment by surfaceflinger** [comment]
```nix
extensions = {
  enableExtraExtensions = true;
  extraExtensions = {
    "{1be309c5-3e4f-4b99-927d-bb500eb4fa88}".install_url = "https://addons.mozilla.org/firefox/downloads/latest/augmented-steam/latest.xpi";
  };
}; 
```

swap the xpi url, change uuid to something new from uuidgen and in I think in `about:policies` you should find an error with the actual expected correct id to put before .install_url

**Comment by NotAShelf** [comment]
Sorry for the lack of attention, I've been extremely busy lately and the other maintainer of Schizofox is MIA as usual.

To clarify, as of [my security and privacy tweaks PR](https://github.com/schizofox/schizofox/commit/becff9b92a28c3cd6e6a215da7f5f56883d3a304) the extensions set has been aggressively refactored.

```nix
extensions = {
  enableExtraExtensions = true;
  enableDefaultExtensions = true;
  extraExtensions = { ... };
}; 
```

By default, both enable options will default to *false* because I didn't want to impose addons on the user - which unlike policies, may be compromised. `defaultExtensions` are the ones we ship with Schizofox, you are not supposed to change the set.

extraExtensions are ones you want to add, but should also be enabled with `enableDefaultExtensions` for your extensions to be loaded. There was no feedback on my PR, but if you think those options should default to true feel free to create an issue or a pull request. I'll get on it as soon as I can.

Lastly, to answer your questions:

> "what extensions can I add in the extensions sections and what extensions do I need to add in extraExtensions"

`programs.schizofox.extensions` is the name of the module - your addons most go into `programs.schizofox.extensions.extraExtensions`. You can add *any* extension as an `.xpi` file, but the manifest ID must be correct for the addon to be loaded. 

I intend to redo the Firefox wrapper soon, which'll allow for a more intuitive addon fetching method.

> What does "webextension@metamask.io".install_url how do I know what the string should be for my file extension.

You can obtain addon IDs (`"webextension@metamask.io"` in this case) from the addon's manifest. Most open-source extension contain a `manifest.json` with their ID - for example, [this is Metamask's](https://github.com/MetaMask/metamask-extension/blob/develop/app/manifest/v2/firefox.json)

**Comment by laycookie** [comment]
@NotAShelf Thank you for the clarifications! I have also completely forgot to ask if it is possible to pin the extension to the toolbar, and if it is impossible is it planned to be added in the future?

**Comment by NotAShelf** [comment]
I was under the impression that *is* possible, since @sioodmy used to include a policy default in the past, though it's not directly supported by the module because I removed it - it didn't work on latest versions of Firefox... 

If I recall correctly, you are able to pin extensions to the toolbar :sparkles: declaratively :sparkles: by sticking JSON in a policy - though I am not sure how, as I prefer addons out of my toolbar. A quick google search lead me to Mozilla's [policy templates repo](https://github.com/mozilla/policy-templates/discussions/1000) with some discussion regarding extension pinning. To me, it looks like it is **not yet possible** to do it declaratively, but you can do it manually by right clicking an extension and choosing "Pin to toolbar".
